apiVersion: v1
kind: Secret
metadata:  
  labels:
    {{- include "boldreports.labels" . | nindent 4 }}
  name: bold-db-secret
{{ include "boldreports.namespace" . | indent 2 }}
type: Opaque
stringData:
  BOLD_SERVICES_DB_TYPE: "{{ .Values.databaseServerDetails.dbType }}"
  BOLD_SERVICES_DB_HOST: "{{ .Values.databaseServerDetails.dbHost }}"
  BOLD_SERVICES_DB_PORT: "{{ .Values.databaseServerDetails.dbPort }}"
  BOLD_SERVICES_POSTGRESQL_MAINTENANCE_DB: "{{ .Values.databaseServerDetails.maintenanceDB }}"
  BOLD_SERVICES_DB_USER: "{{ .Values.databaseServerDetails.dbUser }}"
  BOLD_SERVICES_DB_PASSWORD: "{{ .Values.databaseServerDetails.dbPassword }}"
  BOLD_SERVICES_DB_ADDITIONAL_PARAMETERS: "{{ .Values.databaseServerDetails.dbAdditionalParameters }}"
  BOLD_SERVICES_DB_NAME: "{{ .Values.databaseServerDetails.dbName }}"