{{- if not .Values.licenseKeyDetails.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:  
  labels:
    {{- include "boldreports.labels" . | nindent 4 }}
  name: bold-license-key
{{ include "boldreports.namespace" . | indent 2 }}
type: Opaque
stringData:
  BOLD_SERVICES_UNLOCK_KEY: "{{ .Values.licenseKeyDetails.licenseKey }}"
{{- end }}