{{- if .Values.upgradeCenter.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: boldreports-upgrade-center-playwright
  {{- include "boldreports.namespace" . | nindent 2 }}
  labels:
    helm.sh/chart: {{ .Chart.Name }}_{{ .Chart.Version }}
    app.kubernetes.io/name: boldreports-upgrade-center-playwright
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    {{- end }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  BOLDREPORTS_ADMIN_USERNAME: {{ if .Values.rootUserDetails.email }}{{ .Values.rootUserDetails.email | quote }}{{ else }}{{ .Values.upgradeCenter.secret.BOLDREPORTS_ADMIN_USERNAME | quote }}{{ end }}
  BOLDREPORTS_ADMIN_EMAIL: {{ if .Values.rootUserDetails.email }}{{ .Values.rootUserDetails.email | quote }}{{ else }}{{ .Values.upgradeCenter.secret.BOLDREPORTS_ADMIN_EMAIL | quote }}{{ end }}
  BOLDREPORTS_ADMIN_PASSWORD: {{ if .Values.rootUserDetails.password }}{{ .Values.rootUserDetails.password | quote }}{{ else }}{{ .Values.upgradeCenter.secret.BOLDREPORTS_ADMIN_PASSWORD | quote }}{{ end }}
{{- end }}
